<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-16T10:56:15 IST" name="Suite" finished-at="2024-09-16T10:56:40 IST" duration-ms="24342">
    <groups>
      <group name="EndToEnd">
        <method signature="LoginFunctionalityTest.validLoginMessagetest()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" name="validLoginMessagetest" class="com.ibm.ecommerceapplication.tests.LoginFunctionalityTest"/>
      </group> <!-- EndToEnd -->
      <group name="regression">
        <method signature="LoginFunctionalityTest.invalidLoginMessagetest()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" name="invalidLoginMessagetest" class="com.ibm.ecommerceapplication.tests.LoginFunctionalityTest"/>
        <method signature="LoginFunctionalityTest.validLoginMessagetest()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" name="validLoginMessagetest" class="com.ibm.ecommerceapplication.tests.LoginFunctionalityTest"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="LoginFunctionalityTest.validLoginMessagetest()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" name="validLoginMessagetest" class="com.ibm.ecommerceapplication.tests.LoginFunctionalityTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2024-09-16T10:56:15 IST" name="Test1" finished-at="2024-09-16T10:56:40 IST" duration-ms="24342">
      <class name="com.ibm.ecommerceapplication.tests.LoginFunctionalityTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:15 IST" name="launchApplication" finished-at="2024-09-16T10:56:19 IST" duration-ms="3812" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="invalidLoginMessagetest()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:19 IST" name="invalidLoginMessagetest" finished-at="2024-09-16T10:56:23 IST" duration-ms="3958" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Login Successfully]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Login Successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.ibm.ecommerceapplication.tests.LoginFunctionalityTest.invalidLoginMessagetest(LoginFunctionalityTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginMessagetest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:23 IST" name="tearDown" finished-at="2024-09-16T10:56:24 IST" duration-ms="300" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:24 IST" name="launchApplication" finished-at="2024-09-16T10:56:26 IST" duration-ms="2822" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="invalidLoginMessagetest()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:26 IST" name="invalidLoginMessagetest" finished-at="2024-09-16T10:56:30 IST" duration-ms="3971" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Login Successfully]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Login Successfully]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.ibm.ecommerceapplication.tests.LoginFunctionalityTest.invalidLoginMessagetest(LoginFunctionalityTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginMessagetest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:31 IST" name="tearDown" finished-at="2024-09-16T10:56:31 IST" duration-ms="294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:31 IST" name="launchApplication" finished-at="2024-09-16T10:56:35 IST" duration-ms="3819" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="validLoginMessagetest()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:35 IST" name="validLoginMessagetest" finished-at="2024-09-16T10:56:39 IST" duration-ms="4632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginMessagetest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ibm.ecommerceapplication.tests.LoginFunctionalityTest@480d3575]" started-at="2024-09-16T10:56:39 IST" name="tearDown" finished-at="2024-09-16T10:56:40 IST" duration-ms="295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ibm.ecommerceapplication.tests.LoginFunctionalityTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
